### ISSUE TITLE
Remove unexpected files that appear in peel-analyser folder of peel-bundle

### ISSUE THREAD

**Issue by tammymendt** [stratosphere/peel#28]
When peel is built, a peel-bundle is created in the target of peel-dist. The bundle contains a folder peel-analyser which will contain the database that is created when calling ./peel analyse. However, when building peel, this folder (which should probably be empty) contains  the following files:

ExperimentRuns.jrxml
TaskInstancesHistogramm.jrxml
TestReport.jrxml
TwitterMingliangAllExperiments.jrxml
ReportExternalClass.jrxml
TwitterMingliang.jrxml

**Comment by aalexandrov** [comment]
This is solved in my master, will push upstream this soon.

**Comment by aalexandrov** [comment]
This is going to be fixed as part of the migration of the `peel-analyzer` features into `peel-core` and `peel-extensions`.
