### ISSUE TITLE
JOB Lifespan

### ISSUE THREAD

**Issue by markus-h** [stratosphere/peel#30]
What do you think about a JOB lifespan? For my experiments on fault tolerance I need Flink to be set up freshly before every job run, since I am killing nodes during job execution. Is that something other people might need as well?

**Comment by aalexandrov** [comment]
Makes sense. We can meet and I will show you where to add the code.

**Comment by aalexandrov** [comment]
Resolved by ed186688dadb0770f4842ba8150d4784b74999a4. @markus-h thanks for the fix!
