### ISSUE TITLE
Introduce init/delete for blog storage in flink-0.9.0

### ISSUE THREAD

**Issue by akunft** [stratosphere/peel#36]
Similar to the logic for the tmp directories used for spilling data, we need to integrate the logic to create/delete the directories used for the blob storage introduced in flink 0.9.0.

**Comment by aalexandrov** [comment]
We got this horribly wrong :)

The `blob.storage.directory` parameter is used as storage folder for the BlobServer, which runs solely within the JobManager. Moreover, [the BlobServer initializes the directory itself if it is not created yet](https://github.com/apache/flink/blob/master/flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobUtils.java#L66).

I'll revet the changes (you also reverted some fixes of mine from last night when you pushed your chanages.

**Comment by akunft** [comment]
Good you noticed that, sorry for the reverts :)
