### ISSUE TITLE
Versioning Issue in archetype pom and maven central

### ISSUE THREAD

**Issue by fschueler** [stratosphere/peel#59]
Follwoing the [instructions on the website](http://peel-framework.org/getting-started.html) does not work and leads to the following error when running `mvn clean deploy`

```
[ERROR] Failed to execute goal on project peel-bundle-peelextensions: 
Could not resolve dependencies for project com.acme.peel:peel-bundle-peelextensions:jar:1.0-SNAPSHOT: 
Could not find artifact org.peelframework:peel-core:jar:1.0-SNAPSHOT
```

The version of the module that is deployed at maven central is 1.0.0-beta.

**Comment by aalexandrov** [comment]
This is strange, it works on my machine even if I wipe out `~/.m2/repository/org/peelframework*`. Can you try adding the following piece of code to your root `pom.xml`:

```xml
      <repositories>
        <repository>
          <id>snapshots-repo</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases><enabled>false</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
```

**Comment by fschueler** [comment]
If I wipe out `~/.m2/repository/org/peelframework*` it can't even find the archetype because the example code to create the archetype on the getting started page also sets 1.0-SNAPSHOT as the version for the archetype. I think this could all be fixed by releasing a new peel version and making sure that all versions are consistent.

**Comment by aalexandrov** [comment]
Will do.

**Comment by aalexandrov** [comment]
Done.
