### ISSUE TITLE
Improvements for the "Getting Started" page

### ISSUE THREAD

**Issue by fschueler** [stratosphere/peel#61]
I tried to follow the steps on the [Getting Started](http://peel-framework.org/getting-started.html) page but couldn't get it to run. I think for potential new users it is important that all these steps work out of the box.
What I have observed so far:

- [x] Binary archive is not there (http://peel-framework.org/peel-empty-bundle-1.0-SNAPSHOT.tar.gz).
- [x] Version in the archetype pom.xml file does not fit the dependencies that are available in the maven repo (#60 should fix that).
- [x] Following the archetype setup, the command `./peel.sh suite:run wordcount.default` fails with 
```
No configuration setting found for key 'system.spark.config.defaults.spark.local'
```

Additionally, when I first tried to issue the command using the described steps (and variables for groupid, artifactid and root-package) it failed because it couldn't find a fitting flink-constructur. After using the archetype command from the [Motivation](http://peel-framework.org/manual/motivation.html) page (bottom) it worked...

**Comment by aalexandrov** [comment]
The third issue is fixed via 7639c5aacf3858671d8ae8890dcf9bae11c2c365.

**Comment by aalexandrov** [comment]
The second issue should be fixed via 479ea73c69c534e1332875114b7a781743b8cfa8.

**Comment by aalexandrov** [comment]
The third issue should be fixed if you download the binary from here: 

https://github.com/stratosphere/peel/releases/download/v1.0.0-rc1/peel-empty-bundle-1.0.0-rc1.tar.gz

@fschueler please check whether the things work now and let me know if I can close the issue.

**Comment by fschueler** [comment]
I checked both the archetype and the packaged binaries and everything worked fine :)
