### ISSUE TITLE
Add file copy between two HDFS instances

### ISSUE THREAD

**Issue by akunft** [stratosphere/peel#69]
This enables us to load data sets directly from static HDFS instances to the one used in the experiments. Currently we only have facilities to copy files from local, which is especially limiting in cases the data is to big to fit on a single machine.

As I see it there are basically two options:
1. Introduce a new method to `HDFSFileSystem` and new `HDFSCopiedDataset`
2. Rewrite copy on local for `HDFSFileSystem` to use the appropriate cmd depending on the provided URI

I would prefer the second solution.

**Comment by aalexandrov** [comment]
+1 for the second option

**Comment by trenner** [comment]
As an alternative you can also write a simple Flink job for that (readTextfile ... writeAsText). We did something similar to load datasets with multiple nodes in parallel from SAN to HDFS on wally.

**Comment by akunft** [comment]
Good point. The hadoop cmd `distcp2` I was thinking of is actually also an MR job

**Comment by aalexandrov** [comment]
@akunft If you're not working on that already I'll take over the task.

**Comment by akunft** [comment]
I would do it once I finished #71 #67
