### ISSUE TITLE
Async/bulk copy for distributed log collections

### ISSUE THREAD

**Issue by akunft** [stratosphere/peel#73]
Currently, checking the current offset and transferring the logs is issued sequentially with independent ssh commands. As ssh commands are pretty heavy weight, we should investigate if we replace the current implementations with:

1. ` pssh` command, but I'm not sure if the implementation is more efficient than establishing the independent ssh commands separately. 
2. Asynchronously issue the ssh commands (as `Futures`). This -- maybe -- can also be seen as an addition to option 1, if it turns out `pssh` is more efficient.

**Comment by aalexandrov** [comment]
Unfortunately `pssh` is not on all machines per default, so I would go for option 2, which leaves us with less dependencies to the host environment.

**Comment by aalexandrov** [comment]
[WIP can be found here](https://github.com/aalexandrov/peel/tree/issue_73).

@akunft can you test whether this works?
