### ISSUE TITLE
Add Yarn Experiment

### ISSUE THREAD

**Issue by carabolic** [stratosphere/peel#79]
Add support for Yarn experiments. 

This would make REEF experiment redundant (#76) for now.

**Comment by carabolic** [comment]
This seems to resolve #76 as well. 

Also see [my working example](https://github.com/carabolic/peel-reef-on-yarn), specifically the [experiment definition](https://github.com/carabolic/peel-reef-on-yarn/blob/master/example-bundle/src/main/resources/config/experiments.xml#L23) that is using `YarnExperiment` to run a `REEF` job.

**Comment by aalexandrov** [comment]
@carabolic can you make a PR with your `org.peelframework.hadoop.beans.experiment.YarnExperiment` implementation?

@verbit I think that log collection for Yarn jobs has to be implemented within the `YarnExperiment.SingleJobRun#runJob()` logic, as this is the place where you get a handle on your application ID.
